language: csharp
sudo: false
mono: none
dotnet: 2.1.4
mono: 5.10.0
dist: trusty

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

script:
  - ./build.sh "-target=Travis"

cache:
  directories:
    - .packages
    - tools

notifications:
  email: false
